name: 部署前端到腾讯云 OpenCloudOS 9

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release
    types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 自动部署前端
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/local/client
			git reset --hard
            git checkout release
            git pull
            npm install
            npm run build
            cp -rf dist/* /usr/share/nginx/html/
            echo "✅ 前端自动化部署成功！"